"""
Utilities for loading FedBN-derived hospital domain-sensitivity scores.
"""
from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Dict, Optional


def hospital_short_name(forget_client: str) -> str:
    """Convert Canada_Dataset to the output-directory name Canada."""
    suffix = "_Dataset"

    if forget_client.endswith(suffix):
        return forget_client[:-len(suffix)]

    return forget_client


def build_domain_scores_path(
    source_run: str,
    forget_client: str,
    pooling: str = "equal_hospital",
    output_root: str = "outputs/domain_sensitivity",
) -> str:
    """
    Return the default JSON path generated by
    scripts/analyze_bn_domain_sensitivity.py.
    """
    valid_pooling = {
        "equal_hospital",
        "sample_weighted",
    }

    if pooling not in valid_pooling:
        raise ValueError(
            "pooling must be 'equal_hospital' or "
            f"'sample_weighted', got {pooling!r}."
        )

    return str(
        Path(output_root)
        / pooling
        / source_run
        / hospital_short_name(forget_client)
        / "domain_sensitivity.json"
    )


def load_domain_scores(
    path: str,
    *,
    expected_source_run: Optional[str] = None,
    expected_forget_client: Optional[str] = None,
) -> Dict[str, float]:
    """
    Load:

        associated_parameter -> normalized_domain_score

    from the domain-sensitivity JSON.

    If multiple BN rows map to the same model parameter, the maximum
    domain score is retained.
    """
    json_path = Path(path)

    if not json_path.is_file():
        raise FileNotFoundError(
            f"Domain-sensitivity JSON not found: {json_path}"
        )

    with json_path.open("r", encoding="utf-8") as file:
        payload = json.load(file)

    if not isinstance(payload, dict):
        raise ValueError(
            f"Expected a JSON object in {json_path}."
        )

    metadata = payload.get("metadata", {})

    if metadata is None:
        metadata = {}

    if not isinstance(metadata, dict):
        raise ValueError(
            f"Invalid metadata object in {json_path}."
        )

    actual_source_run = metadata.get("source_run")

    if (
        expected_source_run is not None
        and actual_source_run is not None
        and actual_source_run != expected_source_run
    ):
        raise ValueError(
            "Domain-score source mismatch: "
            f"expected {expected_source_run!r}, "
            f"found {actual_source_run!r}."
        )

    actual_forget_client = metadata.get("forget_client")

    if (
        expected_forget_client is not None
        and actual_forget_client is not None
        and actual_forget_client != expected_forget_client
    ):
        raise ValueError(
            "Domain-score forgotten-hospital mismatch: "
            f"expected {expected_forget_client!r}, "
            f"found {actual_forget_client!r}."
        )

    rows = payload.get("layers")

    if not isinstance(rows, list):
        raise ValueError(
            f"Missing or invalid 'layers' list in {json_path}."
        )

    scores: Dict[str, float] = {}

    for row in rows:
        if not isinstance(row, dict):
            continue

        parameter_name = str(
            row.get("associated_parameter", "")
        ).strip()

        # Some BN modules might not map to an adapter-compatible
        # parameter. Ignore those rows.
        if not parameter_name:
            continue

        try:
            score = float(
                row["normalized_domain_score"]
            )
        except (KeyError, TypeError, ValueError) as exc:
            raise ValueError(
                "Invalid normalized_domain_score for "
                f"{parameter_name!r} in {json_path}."
            ) from exc

        if not math.isfinite(score):
            raise ValueError(
                "Non-finite domain score for "
                f"{parameter_name!r}: {score}."
            )

        # Protect against tiny floating-point excursions.
        score = min(
            1.0,
            max(0.0, score),
        )

        scores[parameter_name] = max(
            scores.get(parameter_name, 0.0),
            score,
        )

    if not scores:
        raise ValueError(
            "No parameter-mapped domain scores were loaded "
            f"from {json_path}."
        )

    return scores
